# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: RunTest

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Start xcode build
      run: |
        xcodebuild clean build -project FoodBowl.xcodeproj -scheme FoodBowl -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2'
